### ISSUE TITLE
Where can i find createBatchedNMSPlugin?

### ISSUE THREAD

**Issue by Lisicong9203** [upczww/YoLov5-TensorRT-NMS#2]
Hi where is the function `createBatchedNMSPlugin` definition  in 198 line in common.hpp

**Comment by upczww** [comment]
It’s TensorRT official plugin.

Lisicong9203 ***@***.***>于2021年4月29日 周四18:33写道：

**Comment by Lisicong9203** [comment]
谢谢，我最近在做 rotate nms 的 plug-in，您最近做过类似的工作吗？

**Comment by upczww** [comment]
createBatchedNMSPlugin is not provided in high version NvInferPlugin.h, I updated the addBatchedNMSLayer().
